
package vista;



public class InterEntradas extends javax.swing.JInternalFrame {

    /**
     * Creates new form InterEntradas
     */
    public InterEntradas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jbtnRegistrar = new javax.swing.JButton();
        jbtnPendiente = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtxtEntrada = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtCantidad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxtPrecioCosto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtxtDocumento = new javax.swing.JTextField();
        jtxtFecha = new com.toedter.calendar.JDateChooser();
        jcbxMotivo = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jtxtObs = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblEntrada = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jtxtIdProducto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jbtnBuscarProducto = new javax.swing.JButton();
        jtxtNombreProducto = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jtxtIdProveedor = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jtxtNombreProveedor = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtxtIdCategoria = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jtxtNombreCategoria = new javax.swing.JTextField();
        jbtnBuscar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        jLabel1.setText("Registro De Entradas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 19, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(50, 130, 181));
        jLabel4.setText("Complete la Informacion de las entradas.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 53, -1, -1));

        jbtnRegistrar.setText("REGISTRAR");
        getContentPane().add(jbtnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, 210, 40));

        jbtnPendiente.setText("PENDIENTE");
        getContentPane().add(jbtnPendiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 610, 130, 40));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("ID Entrada");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jtxtEntrada.setEnabled(false);
        jPanel1.add(jtxtEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 96, -1));

        jLabel3.setText("Motivo");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jtxtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtCantidadKeyReleased(evt);
            }
        });
        jPanel1.add(jtxtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 205, -1));

        jLabel5.setText("Cantidad");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jLabel6.setText("Fecha");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel7.setText("Precio Costo");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jtxtPrecioCosto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtPrecioCostoKeyReleased(evt);
            }
        });
        jPanel1.add(jtxtPrecioCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 205, -1));

        jLabel10.setText("Documento");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));
        jPanel1.add(jtxtDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 205, -1));

        jtxtFecha.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jtxtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 205, -1));

        jcbxMotivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Motivo", "Compra", "Devolucion", "Transferencia de Almacen", "Ajuste de Inventario" }));
        jPanel1.add(jcbxMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 200, 30));

        jLabel18.setText("Obs");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 60, -1));

        jtxtObs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxtObs.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtObs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtObsActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtObs, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 200, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 220, 490));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jtblEntrada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Motivo", "Documento", "IDProducto", "IDCategoria", "IDProveedor", "Fecha", "Cantidad", "Precio Costo", "Obs", "Total"
            }
        ));
        jtblEntrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblEntradaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtblEntradaMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(jtblEntrada);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 823, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, -1, 260));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 43, 153));
        jLabel17.setText("Buscar Producto");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("ID Producto");

        jbtnBuscarProducto.setText("Lupa");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtIdProducto)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel17))
                    .addComponent(jLabel9)
                    .addComponent(jtxtNombreProducto))
                .addContainerGap(101, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(156, Short.MAX_VALUE)
                    .addComponent(jbtnBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(17, 17, 17)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel17)
                .addGap(29, 29, 29)
                .addComponent(jLabel9)
                .addGap(6, 6, 6)
                .addComponent(jtxtIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(168, Short.MAX_VALUE)
                    .addComponent(jbtnBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 240, 220));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(238, 173, 61));
        jLabel14.setText("Datos del Proveedor");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("ID");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 42, -1, -1));
        jPanel5.add(jtxtIdProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 64, 143, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Nombre");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 102, -1, -1));
        jPanel5.add(jtxtNombreProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 124, 143, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 90, 260, 220));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 153, 0));
        jLabel11.setText("Datos de la Categoria ");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 14, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("ID");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 48, -1, -1));
        jPanel3.add(jtxtIdCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 70, 143, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Categoria");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 108, -1, -1));
        jPanel3.add(jtxtNombreCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 130, 143, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 240, 220));

        jbtnBuscar.setText("BUSCAR");
        getContentPane().add(jbtnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 610, 130, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btniconoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btniconoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btniconoActionPerformed

    private void btnBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProductoActionPerformed

    }//GEN-LAST:event_btnBuscarProductoActionPerformed

    private void btnBuscarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCategoriaActionPerformed

    }//GEN-LAST:event_btnBuscarCategoriaActionPerformed

    private void jtblEntradaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblEntradaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jtblEntradaMouseEntered

    private void jtblEntradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblEntradaMouseClicked

    }//GEN-LAST:event_jtblEntradaMouseClicked

    private void jtxtPrecioCostoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPrecioCostoKeyReleased

    }//GEN-LAST:event_jtxtPrecioCostoKeyReleased

    private void jtxtCantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCantidadKeyReleased

    }//GEN-LAST:event_jtxtCantidadKeyReleased

    private void btnBuscaProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaProveedorActionPerformed

    }//GEN-LAST:event_btnBuscaProveedorActionPerformed

    private void jtxtObsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtObsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtObsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton jbtnBuscar;
    public javax.swing.JButton jbtnBuscarProducto;
    public javax.swing.JButton jbtnPendiente;
    public javax.swing.JButton jbtnRegistrar;
    public javax.swing.JComboBox<String> jcbxMotivo;
    public javax.swing.JTable jtblEntrada;
    public javax.swing.JTextField jtxtCantidad;
    public javax.swing.JTextField jtxtDocumento;
    public javax.swing.JTextField jtxtEntrada;
    public com.toedter.calendar.JDateChooser jtxtFecha;
    public javax.swing.JTextField jtxtIdCategoria;
    public javax.swing.JTextField jtxtIdProducto;
    public javax.swing.JTextField jtxtIdProveedor;
    public javax.swing.JTextField jtxtNombreCategoria;
    public javax.swing.JTextField jtxtNombreProducto;
    public javax.swing.JTextField jtxtNombreProveedor;
    public javax.swing.JTextField jtxtObs;
    public javax.swing.JTextField jtxtPrecioCosto;
    // End of variables declaration//GEN-END:variables
}
